#line 2 "Sources/rez_scanner.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 128
#define YY_END_OF_BUFFER 129
static yyconst short int yy_acclist[501] =
    {   0,
       79,   79,  101,  101,   95,   95,  122,  122,  129,  127,
      128,  126,  127,  128,  126,  128,  127,  128,   67,  127,
      128,  127,  128,  127,  128,  127,  128,   89,  127,  128,
      127,  128,  110,  127,  128,  110,  127,  128,  117,  127,
      128,  127,  128,  118,  127,  128,   41,  127,  128,   41,
      127,  128,   41,  127,  128,   41,  127,  128,   41,  127,
      128,   41,  127,  128,   41,  127,  128,   41,  127,  128,
       41,  127,  128,   41,  127,  128,   41,  127,  128,   41,
      127,  128,   41,  127,  128,   41,  127,  128,   41,  127,
      128,   41,  127,  128,   41,  127,  128,   41,  127,  128,

      127,  128,   83,  128,   69,  128,   68,  128,   79,  128,
       88,  128,  128,   87,   88,  128,   85,   88,  128,   88,
      128,  101,  128,  103,  128,  102,  128,   99,  128,   90,
       99,  128,   95,   99,  128,  128,  122,  128,  126,  114,
       84,  107,  112,  100,  105,  108,  110,  110,  115,  119,
      113,  120,  116,   41,   41,   41,    3,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,  111,   83,   82,   82,   82,
       82,   78,   82,   80,   82,   76,   82,   77,   82,   75,

       82,   81,   82,   86,  101,  102,  102,  104,   98,   94,
       98,   96,   98,   92,   98,   93,   98,   91,   98,   97,
       98,  123,  122,  107,  105,  108,  110,  109,  106,   41,
       41,   41,    5,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   18,   41,   41,   41,   22,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   32,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   51,
      107,  108,  110,  109,  106,   41,   41,   41,   41,   41,
        8,   41,    9,   41,   41,   11,   41,   41,   41,   41,
       41,   41,   17,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   29,   41,   30,   41,   41,   41,   41,
       35,   41,   36,   41,   41,   38,   41,   39,   41,   41,
       74,   71,   70,   48,  107,  108,  110,  109,  106,    1,
       41,    2,   41,   41,   41,   41,   41,   41,   41,   41,
       15,   41,   16,   41,   41,   41,   41,   41,   41,   41,
       26,   41,   27,   41,   41,   41,   41,   41,   41,   41,
       73,   45,   47,   50,   52,   55,   61,   62,   65,   66,
      107,  108,  110,  109,  106,    4,   41,   41,   41,   10,
       41,   41,   41,   14,   41,   41,   41,   41,   41,   41,
       25,   41,   41,   41,   33,   41,   34,   41,   41,   41,

       72,   60,  107,  108,  110,  109,  106,   41,    7,   41,
       12,   41,   13,   41,   41,   21,   41,   20,   41,   23,
       41,   24,   41,   28,   41,   41,   41,   40,   41,   49,
       53,   54,   59,  107,  108,  110,  109,  106,   41,   41,
       31,   41,   37,   41,   46,   63,   64,  107,  108,  110,
      109,  106,    6,   41,   19,   41,  124,  121,   44,   57,
      108,  110,  109,  106,  125,  125,  108,  110,  109,   42,
       43,   56,  108,  110,  109,  108,  110,  109,   58,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109

    } ;

static yyconst short int yy_accept[498] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    5,    6,
        7,    8,    9,   10,   12,   15,   17,   19,   22,   24,
       26,   28,   31,   33,   36,   39,   42,   44,   47,   50,
       53,   56,   59,   62,   65,   68,   71,   74,   77,   80,
       83,   86,   89,   92,   95,   98,  101,  103,  105,  107,
      109,  111,  113,  114,  117,  120,  122,  124,  126,  128,
      130,  133,  136,  137,  139,  140,  141,  141,  141,  142,
      142,  143,  144,  145,  146,  148,  149,  149,  149,  150,
      151,  152,  153,  154,  155,  156,  157,  159,  160,  161,
      162,  163,  164,  165,  166,  167,  168,  169,  170,  171,

      172,  173,  174,  175,  176,  177,  178,  179,  180,  181,
      182,  183,  184,  185,  186,  187,  188,  189,  190,  191,
      192,  194,  196,  198,  200,  202,  204,  205,  206,  207,
      208,  209,  210,  212,  214,  216,  218,  220,  222,  222,
      223,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  225,  226,  228,  229,  230,  231,  232,  233,  235,
      236,  237,  238,  239,  240,  241,  242,  243,  244,  245,
      247,  248,  249,  251,  252,  253,  254,  255,  256,  257,
      258,  259,  260,  262,  263,  264,  265,  266,  267,  268,

      269,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  272,  274,  275,  276,  277,  278,  279,  280,  281,
      283,  285,  286,  288,  289,  290,  291,  292,  293,  295,
      296,  297,  298,  299,  300,  301,  302,  303,  304,  306,
      308,  309,  310,  311,  313,  315,  316,  318,  320,  321,
      322,  323,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  326,

      328,  329,  330,  332,  334,  335,  336,  337,  338,  339,
      340,  341,  343,  345,  346,  347,  348,  349,  350,  351,
      353,  355,  356,  357,  358,  359,  360,  361,  361,  362,
      362,  362,  362,  362,  362,  363,  363,  364,  364,  365,
      366,  366,  367,  367,  367,  367,  367,  368,  369,  369,
      369,  370,  371,  372,  374,  375,  376,  378,  379,  380,
      382,  383,  384,  386,  387,  388,  389,  390,  391,  393,
      394,  395,  397,  399,  400,  401,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  403,  403,
      403,  404,  406,  407,  408,  409,  411,  413,  415,  416,

      418,  420,  422,  424,  426,  427,  428,  430,  430,  430,
      430,  430,  430,  430,  431,  433,  433,  433,  434,  434,
      434,  435,  437,  438,  439,  440,  441,  443,  445,  445,
      445,  445,  445,  445,  446,  446,  446,  447,  448,  449,
      451,  452,  453,  455,  457,  457,  458,  458,  459,  459,
      459,  460,  460,  461,  463,  464,  465,  466,  467,  467,
      467,  467,  467,  469,  470,  471,  472,  473,  473,  475,
      476,  476,  478,  479,  480,  481,  482,  483,  484,  485,
      486,  487,  488,  489,  490,  491,  492,  493,  494,  495,
      496,  497,  498,  499,  500,  501,  501

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    1,   10,   11,   12,
        1,   13,    1,    1,    1,    1,   14,   15,   16,   17,
       17,   17,   17,   17,   17,   18,   18,    1,    1,   19,
       20,   21,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   23,   33,   34,   35,   36,   37,   38,
       23,   39,   40,   41,   42,   43,   44,   45,   46,   47,
        1,   22,    1,    1,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   23,   33,   34,   35,   36,
       37,   38,   23,   39,   40,   41,   42,   43,   44,   45,
       46,   47,    1,   48,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    2,    3,    1,    2,    1,    4,    1,    1,    1,
        1,    5,    6,    1,    7,    7,    7,    7,    1,    1,
        1,    4,    8,    9,    9,    9,    9,    9,    9,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1
    } ;

static yyconst short int yy_base[533] =
    {   0,
        0,    0,   46,   47,   67,   94,   48,   49,   53,   54,
      100,  122,  796,  797,   75,   84,  775,  797,   28,  123,
      784,  797,   45,  118,   98,   47,  773,  124,    0,  119,
      123,  130,  764,   39,  763,  754,  761,   94,  756,  761,
      125,  758,  123,  127,  749,  139,  736,    0,  797,  797,
      171,  797,  797,  797,  797,    0,    0,  797,  143,  797,
      797,  156,  776,  170,  199,  797,  754,  745,  797,  191,
        0,  797,  797,    0,  223,  227,  162,    0,  797,  797,
      797,  797,  797,    0,  748,  740,    0,  101,  741,  736,
      736,  751,  733,  172,  739,  738,  726,  142,  724,  728,

      732,  742,  725,  733,  723,  222,  724,  730,  719,  722,
      719,  731,  718,  715,  797,    0,  797,    0,  234,  174,
      797,  797,  797,  797,  797,  797,  797,    0,  180,  195,
      797,  797,  797,  797,  797,  797,  797,  797,  748,  797,
      219,  725,  727,   59,   58,  715,  727,  713,  712,  721,
      710,  714,  721,  720,  715,  205,  173,  714,   80,  713,
        0,    0,  237,  241,    0,  710,  715,  714,  697,  702,
      707,  706,  224,  694,  700,  703,  702,  689,  694,  687,
      692,  697,    0,  696,  693,  697,  697,  684,  680,  691,
      676,  679,    0,  683,  673,  685,  684,  679,  682,  682,

      669,    0,  249,  252,  255,    0,  675,  672,  666,  663,
      662,  661,  659,  234,  661,  657,  797,  662,  661,  661,
      669,  654,  667,  664,  656,  652,  650,  660,  648,  662,
        0,  266,  261,    0,  649,  638,  644,  641,  653,    0,
        0,  650,    0,  647,  643,  636,  629,  647,    0,  633,
      631,  642,  632,  638,  635,  634,  626,  634,    0,    0,
      623,  628,  637,    0,    0,  632,    0,    0,  629,  797,
      797,  270,  272,    0,  624,  617,  634,  618,  627,  627,
      618,  625,  797,  617,  612,  620,  607,  620,  614,  609,
      608,  610,  615,  614,  601,  607,  612,  599,    0,  276,

      280,    0,    0,    0,  591,  597,  611,  606,  597,  608,
      603,    0,    0,  591,  602,  600,  603,  590,  597,    0,
        0,  588,  584,  592,  590,  584,  583,  282,  797,  590,
      590,  570,  583,  582,  797,  572,  797,  588,  797,  797,
      570,  797,  582,  567,  572,  573,  797,  797,  568,  569,
      797,  797,    0,  286,  290,    0,    0,  559,  553,    0,
      558,  551,    0,  550,  550,  538,  542,  534,    0,  544,
      545,    0,    0,  540,  535,  797,  305,  534,  527,  531,
      525,  513,  506,  516,  514,  499,  508,  797,  495,  505,
        0,  296,  293,    0,  485,    0,    0,    0,  481,    0,

        0,    0,    0,    0,  481,  481,    0,  313,  314,  464,
      449,  451,  453,  797,  797,  438,  444,  797,  426,  415,
        0,  305,  309,    0,  320,  305,    0,    0,  324,  325,
      290,  237,  247,  797,  226,  219,  797,  797,  797,  322,
      318,    0,    0,    0,  326,  797,  339,  797,  200,  185,
      797,  137,  142,  330,  327,  797,    0,  347,  129,  106,
      100,   74,  338,  342,  797,  797,  797,   34,  344,  348,
       45,  350,  354,  797,  356,  358,  360,  362,  364,  366,
      368,  370,  372,  374,  376,  378,  380,  382,  384,  386,
      388,  390,  392,  394,  797,  797,  410,  419,  428,  437,

      446,  449,  458,  467,  470,  479,  488,  497,  506,  509,
      518,  521,  524,  527,  530,  533,  536,  539,  542,  545,
      548,  551,  554,  557,  560,  563,  571,  574,  577,  585,
      588,  597
    } ;

static yyconst short int yy_def[533] =
    {   0,
      496,    1,  497,  497,  498,  498,  499,  499,  500,  500,
      501,  501,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  496,  503,  496,  496,
      504,  496,  496,  496,  496,  505,  506,  496,  507,  496,
      496,  508,  509,  496,  496,  496,  496,  496,  496,  496,
      510,  496,  496,  511,  496,  496,  496,  512,  496,  496,
      496,  496,  496,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,

      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  496,  503,  496,  513,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  506,  507,  507,
      496,  496,  496,  496,  496,  496,  496,  496,  509,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      514,  511,  496,  496,  515,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,

      502,  516,  496,  496,  496,  517,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      518,  496,  496,  519,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  496,
      496,  496,  496,  520,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  521,  496,

      496,  522,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  523,  496,  496,  524,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      525,  496,  496,  526,  502,  502,  502,  502,  502,  502,

      502,  502,  502,  502,  502,  502,  502,  527,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      528,  496,  496,  529,  502,  502,  502,  502,  530,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  531,  502,  502,  532,  496,  530,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  532,  532,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,    0,  496,  496,  496,  496,

      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496
    } ;

static yyconst short int yy_nxt[846] =
    {   0,
       14,   15,   16,   15,   15,   17,   18,   19,   20,   21,
       22,   14,   14,   23,   24,   25,   25,   25,   26,   27,
       28,   14,   29,   30,   31,   32,   33,   29,   34,   29,
       35,   36,   37,   38,   29,   39,   40,   41,   42,   43,
       44,   45,   29,   46,   29,   29,   29,   47,   49,   49,
       58,   58,   50,   50,   67,   53,   53,   73,   74,   68,
       59,   59,   95,   61,   61,   79,   80,   51,   51,   53,
       96,   54,  474,   55,   62,   62,   65,   65,   65,   65,
      471,   56,   56,   56,   56,   65,   65,   65,   65,  211,
       56,   56,   56,   56,   56,   56,   53,  209,   54,  210,

       55,   64,   53,  212,   64,  468,   53,  228,   56,   56,
       56,   56,   76,   76,   76,   76,  229,   56,   56,   56,
       56,   56,   56,   64,   53,  100,   64,  467,   53,   69,
      101,   70,   75,   75,   75,   76,  168,   71,   71,   71,
       71,  169,   77,   82,   83,  466,   71,   71,   71,   71,
       71,   71,   85,   91,   88,  130,  131,   86,   87,   89,
       92,  104,   78,  107,  105,  109,  108,  181,   90,   93,
      112,  141,  110,  465,  141,  113,  164,  164,  114,  118,
      133,  462,  182,  461,  134,  119,  120,  120,  203,  203,
      203,  135,  496,  496,  136,  121,  137,  175,  138,  122,

       65,   65,   65,   65,  225,  176,  123,  130,  131,  124,
      177,  125,  460,  126,  144,  145,  146,  147,  226,  148,
      141,  149,  150,  141,  151,  152,  153,  459,  154,  155,
      156,  157,  223,  158,  159,  224,  160,  163,  163,  163,
       76,   76,   76,   76,   76,  190,  453,  191,  203,  203,
      203,  232,  232,  232,   76,  233,  233,  452,  204,  242,
      205,  192,  243,  271,  271,  271,  272,  272,  193,  273,
      273,  273,  273,  451,  282,  301,  301,  450,  206,  283,
      300,  300,  300,   76,  272,  272,  328,  328,  328,  328,
      354,  354,  354,   76,  355,  355,  376,  376,  376,  376,

      392,  392,  392,   76,  393,  393,  408,  423,  423,  408,
      422,  422,  422,   76,  408,  430,  449,  408,  430,  440,
      440,  440,   76,  441,  441,  445,  430,  458,  445,  430,
      458,  448,  455,  455,  444,  446,  454,  454,  454,   76,
      445,  464,  464,  445,  463,  463,  463,   76,  458,  443,
      446,  458,  469,  469,  469,   76,  470,  470,  472,  472,
      472,   76,  473,  473,   76,   76,   76,   76,  475,  475,
      476,  476,  477,  477,  478,  478,  479,  479,  480,  480,
      481,  481,  482,  482,  483,  483,  484,  484,  485,  485,
      486,  486,  487,  487,  488,  488,  489,  489,  490,  490,

      491,  491,  492,  492,  493,  493,  494,  494,  495,  495,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   84,   84,   84,  116,  116,
      438,  437,  116,  116,  116,  116,  116,  117,  117,  436,
      117,  117,  117,  117,  117,  117,  127,  435,  127,  128,
      128,  434,  128,  128,  433,  128,  128,  128,  129,  129,
      432,  129,  129,  129,  129,  129,  129,  132,  132,  431,

      132,  132,  132,  132,  132,  132,  139,  428,  427,  139,
      139,  139,  139,  139,  139,  161,  426,  161,  162,  162,
      425,  162,  162,  162,  162,  162,  162,  165,  420,  165,
      202,  419,  202,  231,  418,  231,  234,  417,  234,  270,
      416,  270,  274,  415,  274,  299,  414,  299,  302,  413,
      302,  329,  412,  329,  353,  411,  353,  356,  410,  356,
      391,  409,  391,  394,  407,  394,  421,  406,  421,  424,
      405,  424,  429,  404,  403,  402,  401,  400,  429,  429,
      439,  399,  439,  442,  398,  442,  447,  397,  396,  447,
      395,  447,  447,  447,  456,  390,  456,  457,  457,  389,

      457,  457,  457,  457,  457,  457,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,

      281,  280,  279,  278,  277,  276,  275,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  241,  240,  239,  238,  237,  236,  235,
      230,  227,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  208,  207,  140,  201,  200,  199,  198,  197,
      196,  195,  194,  189,  188,  187,  186,  185,  184,  183,
      180,  179,  178,  174,  173,  172,  171,  170,  167,  166,
      143,  142,  140,  115,  111,  106,  103,  102,   99,   98,
       97,   94,   81,   72,   66,  496,   13,  496,  496,  496,

      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496
    } ;

static yyconst short int yy_chk[846] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        7,    8,    3,    4,   19,    9,   10,   23,   23,   19,
        7,    8,   34,    9,   10,   26,   26,    3,    4,    5,
       34,    5,  471,    5,    9,   10,   15,   15,   15,   15,
      468,    5,    5,    5,    5,   16,   16,   16,   16,  145,
        5,    5,    5,    5,    5,    5,    6,  144,    6,  144,

        6,   11,   11,  145,   11,  462,   11,  159,    6,    6,
        6,    6,   25,   25,   25,   25,  159,    6,    6,    6,
        6,    6,    6,   12,   12,   38,   12,  461,   12,   20,
       38,   20,   24,   24,   24,   24,   88,   20,   20,   20,
       20,   88,   24,   28,   28,  460,   20,   20,   20,   20,
       20,   20,   30,   32,   31,   59,   59,   30,   30,   31,
       32,   41,   24,   43,   41,   44,   43,   98,   31,   32,
       46,   64,   44,  459,   64,   46,   77,   77,   46,   51,
       62,  453,   98,  452,   62,   51,   51,   51,  120,  120,
      120,   62,  129,  129,   62,   51,   62,   94,   62,   51,

       65,   65,   65,   65,  157,   94,   51,  130,  130,   51,
       94,   51,  450,   51,   70,   70,   70,   70,  157,   70,
      141,   70,   70,  141,   70,   70,   70,  449,   70,   70,
       70,   70,  156,   70,   70,  156,   70,   75,   75,   75,
       75,   76,   76,   76,   76,  106,  436,  106,  119,  119,
      119,  163,  163,  163,  163,  164,  164,  435,  119,  173,
      119,  106,  173,  203,  203,  203,  204,  204,  106,  205,
      205,  205,  205,  433,  214,  233,  233,  432,  119,  214,
      232,  232,  232,  232,  272,  272,  273,  273,  273,  273,
      300,  300,  300,  300,  301,  301,  328,  328,  328,  328,

      354,  354,  354,  354,  355,  355,  377,  393,  393,  377,
      392,  392,  392,  392,  408,  409,  431,  408,  409,  422,
      422,  422,  422,  423,  423,  429,  430,  445,  429,  430,
      445,  430,  441,  441,  426,  429,  440,  440,  440,  440,
      447,  455,  455,  447,  454,  454,  454,  454,  458,  425,
      447,  458,  463,  463,  463,  463,  464,  464,  469,  469,
      469,  469,  470,  470,  472,  472,  472,  472,  473,  473,
      475,  475,  476,  476,  477,  477,  478,  478,  479,  479,
      480,  480,  481,  481,  482,  482,  483,  483,  484,  484,
      485,  485,  486,  486,  487,  487,  488,  488,  489,  489,

      490,  490,  491,  491,  492,  492,  493,  493,  494,  494,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  502,  502,  502,  503,  503,
      420,  419,  503,  503,  503,  503,  503,  504,  504,  417,
      504,  504,  504,  504,  504,  504,  505,  416,  505,  506,
      506,  413,  506,  506,  412,  506,  506,  506,  507,  507,
      411,  507,  507,  507,  507,  507,  507,  508,  508,  410,

      508,  508,  508,  508,  508,  508,  509,  406,  405,  509,
      509,  509,  509,  509,  509,  510,  399,  510,  511,  511,
      395,  511,  511,  511,  511,  511,  511,  512,  390,  512,
      513,  389,  513,  514,  387,  514,  515,  386,  515,  516,
      385,  516,  517,  384,  517,  518,  383,  518,  519,  382,
      519,  520,  381,  520,  521,  380,  521,  522,  379,  522,
      523,  378,  523,  524,  375,  524,  525,  374,  525,  526,
      371,  526,  527,  370,  368,  367,  366,  365,  527,  527,
      528,  364,  528,  529,  362,  529,  530,  361,  359,  530,
      358,  530,  530,  530,  531,  350,  531,  532,  532,  349,

      532,  532,  532,  532,  532,  532,  346,  345,  344,  343,
      341,  338,  336,  334,  333,  332,  331,  330,  327,  326,
      325,  324,  323,  322,  319,  318,  317,  316,  315,  314,
      311,  310,  309,  308,  307,  306,  305,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  282,  281,  280,  279,  278,  277,  276,  275,
      269,  266,  263,  262,  261,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  248,  247,  246,  245,  244,  242,
      239,  238,  237,  236,  235,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  216,  215,

      213,  212,  211,  210,  209,  208,  207,  201,  200,  199,
      198,  197,  196,  195,  194,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  172,  171,  170,  169,  168,  167,  166,
      160,  158,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  143,  142,  139,  114,  113,  112,  111,  110,
      109,  108,  107,  105,  104,  103,  102,  101,  100,   99,
       97,   96,   95,   93,   92,   91,   90,   89,   86,   85,
       68,   67,   63,   47,   45,   42,   40,   39,   37,   36,
       35,   33,   27,   21,   17,   13,  496,  496,  496,  496,

      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  496,  496,  496
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Sources/rez_scanner.l"
#define INITIAL 0
#line 2 "Sources/rez_scanner.l"

/*	$Id$
	
	Copyright 1996, 1997, 1998
	        Hekkelman Programmatuur B.V.  All rights reserved.
	
	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are met:
	1. Redistributions of source code must retain the above copyright notice,
	   this list of conditions and the following disclaimer.
	2. Redistributions in binary form must reproduce the above copyright notice,
	   this list of conditions and the following disclaimer in the documentation
	   and/or other materials provided with the distribution.
	3. All advertising materials mentioning features or use of this software
	   must display the following acknowledgement:
	   
	    This product includes software developed by Hekkelman Programmatuur B.V.
	
	4. The name of Hekkelman Programmatuur B.V. may not be used to endorse or
	   promote products derived from this software without specific prior
	   written permission.
	
	THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
	INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
	FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
	AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
	EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
	PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
	OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
	WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
	OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
	ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 	

	Created: 12/02/98 15:37:52
*/

#include "rez.h"
#include "RTypes.h"
#include "rez_parser.cpp.h"
#include "SymbolTable.h"
#include <support/Debug.h>
#include <map>
#include <ctype.h>
#include <time.h>

#define yywrap()	1

static char sBuf[1024], *sbp, *d;

#define MAX_INCLUDE_DEPTH 10
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int include_lineno_stack[MAX_INCLUDE_DEPTH];
char *gFileName[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;

#define MAX_MACRO_DEPTH 10
YY_BUFFER_STATE macro_stack[MAX_MACRO_DEPTH];
int macro_stack_ptr = 0;

typedef map<int, char*> macromap ;
macromap gMacroTable = *new macromap;

void AddMacro(char *s);
void CopyBuf();

#define string 1

#define hexstring 2

#define comment 3

#define cc 4

#define incl 5

#line 864 "Sources/rez_scanner.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 85 "Sources/rez_scanner.l"

														time_t now; time(&now); struct tm *now_t = localtime(&now);
#line 1018 "Sources/rez_scanner.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 497 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 797 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 87 "Sources/rez_scanner.l"
return ALIGN;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 88 "Sources/rez_scanner.l"
return ARRAY;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 89 "Sources/rez_scanner.l"
return AS;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 90 "Sources/rez_scanner.l"
return BINARY;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "Sources/rez_scanner.l"
return BIT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "Sources/rez_scanner.l"
return BITSTRING;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "Sources/rez_scanner.l"
return BOOLEAN;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "Sources/rez_scanner.l"
return BYTE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "Sources/rez_scanner.l"
return CASE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 96 "Sources/rez_scanner.l"
return CHANGE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 97 "Sources/rez_scanner.l"
return CHAR;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 98 "Sources/rez_scanner.l"
return CSTRING;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 99 "Sources/rez_scanner.l"
return DECIMAL;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "Sources/rez_scanner.l"
return DELETE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "Sources/rez_scanner.l"
return DEREZ;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 102 "Sources/rez_scanner.l"
yylval = false; return NUMBER;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "Sources/rez_scanner.l"
return FILL;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "Sources/rez_scanner.l"
return HEX;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 105 "Sources/rez_scanner.l"
return HEXSTRING;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "Sources/rez_scanner.l"
return INTEGER;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "Sources/rez_scanner.l"
return INCLUDE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "Sources/rez_scanner.l"
return KEY;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "Sources/rez_scanner.l"
return LITERAL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "Sources/rez_scanner.l"
return LONGINT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "Sources/rez_scanner.l"
return NIBBLE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "Sources/rez_scanner.l"
return OCTAL;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "Sources/rez_scanner.l"
return POINT;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 114 "Sources/rez_scanner.l"
return PSTRING;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 115 "Sources/rez_scanner.l"
return READ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 116 "Sources/rez_scanner.l"
return RECT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 117 "Sources/rez_scanner.l"
return RES;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "Sources/rez_scanner.l"
return REZ;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 119 "Sources/rez_scanner.l"
return STRING;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 "Sources/rez_scanner.l"
return SWITCH;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 "Sources/rez_scanner.l"
yylval = true; return NUMBER;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 "Sources/rez_scanner.l"
return rTYPE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 "Sources/rez_scanner.l"
return UNSIGNED;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 124 "Sources/rez_scanner.l"
return WIDE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "Sources/rez_scanner.l"
return WORD;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "Sources/rez_scanner.l"
return WSTRING;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "Sources/rez_scanner.l"
{
															yylval = ST_AddIdent(yytext);
															
															if (gMacroTable.find(yylval) != gMacroTable.end())
															{
																if (macro_stack_ptr >= MAX_INCLUDE_DEPTH)
																	error("Macro's nested too deeply");
	
																macro_stack[macro_stack_ptr++] = YY_CURRENT_BUFFER;
																yy_switch_to_buffer(yy_scan_string(gMacroTable[yylval]));
															}
															else
																return IDENT;
														}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 141 "Sources/rez_scanner.l"
return ARRAYINDEX;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 142 "Sources/rez_scanner.l"
warn("attributes are not supported"); yylval = 0; return NUMBER;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 143 "Sources/rez_scanner.l"
return LBITFIELD;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 144 "Sources/rez_scanner.l"
return LBYTE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 145 "Sources/rez_scanner.l"
return COUNTOF;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 146 "Sources/rez_scanner.l"
strftime(sBuf, 1023, "%A, %B %d, %Y", now_t); yylval = (int)strdup(sBuf); return STR_CONST;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 147 "Sources/rez_scanner.l"
yylval = now_t->tm_mday; return NUMBER;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 148 "Sources/rez_scanner.l"
return FORMAT;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 149 "Sources/rez_scanner.l"
yylval = now_t->tm_hour; return NUMBER;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 150 "Sources/rez_scanner.l"
yylval = gResID; return NUMBER;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 151 "Sources/rez_scanner.l"
return LLONG;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 152 "Sources/rez_scanner.l"
yylval = now_t->tm_min; return NUMBER;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 153 "Sources/rez_scanner.l"
yylval = now_t->tm_mon; return NUMBER;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 154 "Sources/rez_scanner.l"
yylval = (int)gResName; return STR_CONST;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 155 "Sources/rez_scanner.l"
warn("packedsize is not supported"); yylval = 0; return NUMBER;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 156 "Sources/rez_scanner.l"
return RESOURCE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 157 "Sources/rez_scanner.l"
return RESSIZE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 158 "Sources/rez_scanner.l"
yylval = now_t->tm_sec; return NUMBER;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 159 "Sources/rez_scanner.l"
return SHELL;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 160 "Sources/rez_scanner.l"
strftime(sBuf, 1023, "%H:%M:%S", now_t); yylval = (int)strdup(sBuf); return STR_CONST;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 161 "Sources/rez_scanner.l"
yylval = gResType; return NUMBER;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 162 "Sources/rez_scanner.l"
yylval = (int)"rez for be 1.0a2"; return STR_CONST;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 163 "Sources/rez_scanner.l"
yylval = now_t->tm_wday; return NUMBER;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 164 "Sources/rez_scanner.l"
return LWORD;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 165 "Sources/rez_scanner.l"
yylval = now_t->tm_year; return NUMBER;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 166 "Sources/rez_scanner.l"
BEGIN(string); sbp = sBuf;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 167 "Sources/rez_scanner.l"
BEGIN(INITIAL); *sbp = 0; yylval = (int)strdup(sBuf); return STR_CONST;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 168 "Sources/rez_scanner.l"
REJECT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 169 "Sources/rez_scanner.l"
*sbp++ = strtol(yytext + 3, &d, 2);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 170 "Sources/rez_scanner.l"
*sbp++ = strtol(yytext + 1, &d, 8);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 171 "Sources/rez_scanner.l"
*sbp++ = strtol(yytext + 3, &d, 10);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 172 "Sources/rez_scanner.l"
*sbp++ = strtol(yytext + 3, &d, 16);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 173 "Sources/rez_scanner.l"
*sbp++ = strtol(yytext + 2, &d, 16);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 174 "Sources/rez_scanner.l"
*sbp++ = '\t';
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 175 "Sources/rez_scanner.l"
*sbp++ = '\n';
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 176 "Sources/rez_scanner.l"
*sbp++ = '\r';
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 177 "Sources/rez_scanner.l"
*sbp++ = 0x08;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 178 "Sources/rez_scanner.l"
*sbp++ = 0x7F;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 179 "Sources/rez_scanner.l"
*sbp++ = 0x0C;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 180 "Sources/rez_scanner.l"
*sbp++ = 0x0B;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 181 "Sources/rez_scanner.l"
*sbp++ = yytext[1];
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 182 "Sources/rez_scanner.l"
strcpy(sbp, yytext); sbp += yyleng;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 183 "Sources/rez_scanner.l"
BEGIN(hexstring); sbp = sBuf + sizeof(long);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 184 "Sources/rez_scanner.l"
BEGIN(INITIAL); CopyBuf(); return HEX_CONST;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 185 "Sources/rez_scanner.l"
*sbp++ = strtol(yytext, &d, 16);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 186 "Sources/rez_scanner.l"

	YY_BREAK
case 88:
YY_RULE_SETUP
#line 187 "Sources/rez_scanner.l"
error("Illegal character inside hexstring: %c (%d)", *yytext, *yytext);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 188 "Sources/rez_scanner.l"
BEGIN(cc); yylval = 0;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 189 "Sources/rez_scanner.l"
BEGIN(INITIAL); return NUMBER;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 190 "Sources/rez_scanner.l"
yylval = (yylval << 8) | '\t';
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 191 "Sources/rez_scanner.l"
yylval = (yylval << 8) | '\n';
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 192 "Sources/rez_scanner.l"
yylval = (yylval << 8) | '\r';
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 193 "Sources/rez_scanner.l"
yylval = (yylval << 8) | 0x08;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 194 "Sources/rez_scanner.l"
yylval = (yylval << 8) | 0x7F;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 195 "Sources/rez_scanner.l"
yylval = (yylval << 8) | 0x0C;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 196 "Sources/rez_scanner.l"
yylval = (yylval << 8) | 0x0B;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 197 "Sources/rez_scanner.l"
yylval = (yylval << 8) | yytext[1];
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 198 "Sources/rez_scanner.l"
yylval = (yylval << 8) | yytext[0];
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 199 "Sources/rez_scanner.l"
BEGIN(comment);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 200 "Sources/rez_scanner.l"

	YY_BREAK
case 102:
YY_RULE_SETUP
#line 201 "Sources/rez_scanner.l"

	YY_BREAK
case 103:
YY_RULE_SETUP
#line 202 "Sources/rez_scanner.l"

	YY_BREAK
case 104:
YY_RULE_SETUP
#line 203 "Sources/rez_scanner.l"
BEGIN(INITIAL);
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 204 "Sources/rez_scanner.l"

	YY_BREAK
case 106:
YY_RULE_SETUP
#line 205 "Sources/rez_scanner.l"
yylval = strtol(yytext + 2, &d, 16); return NUMBER;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 206 "Sources/rez_scanner.l"
yylval = strtol(yytext + 1, &d, 16); return NUMBER;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 207 "Sources/rez_scanner.l"
yylval = strtol(yytext, &d, 8); return NUMBER;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 208 "Sources/rez_scanner.l"
yylval = strtol(yytext + 2, &d, 2); return NUMBER;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 209 "Sources/rez_scanner.l"
yylval = strtol(yytext, &d, 10); return NUMBER;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 210 "Sources/rez_scanner.l"
return OR;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 211 "Sources/rez_scanner.l"
return AND;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 212 "Sources/rez_scanner.l"
return EQ;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 213 "Sources/rez_scanner.l"
return NE;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 214 "Sources/rez_scanner.l"
return SHL;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 215 "Sources/rez_scanner.l"
return SHR;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 216 "Sources/rez_scanner.l"
return LT;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 217 "Sources/rez_scanner.l"
return GT;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 218 "Sources/rez_scanner.l"
return LE;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 219 "Sources/rez_scanner.l"
return GE;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 220 "Sources/rez_scanner.l"
BEGIN(incl);
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 221 "Sources/rez_scanner.l"

	YY_BREAK
case 123:
YY_RULE_SETUP
#line 222 "Sources/rez_scanner.l"
{
															if (include_stack_ptr >= MAX_INCLUDE_DEPTH)
																error("Includes nested too deeply");

															include_lineno_stack[include_stack_ptr] = yylineno;
															include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
															yytext[yyleng - 1] = 0;
															char **i = gIncludePaths;
															char p[PATH_MAX];
															
															do
															{
																strcpy(p, *i++);
																strcat(p, "/");
																strcat(p, yytext);
	
																yyin = fopen(p, "r");
															}
															while (yyin == NULL && *i);
															
															if (yyin == NULL) error("Could not open file %s for input", yytext);
															gFileName[include_stack_ptr - 1] = strdup(p);
															
															yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
															BEGIN(INITIAL);
														}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
case YY_STATE_EOF(hexstring):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(cc):
case YY_STATE_EOF(incl):
#line 248 "Sources/rez_scanner.l"
{
															if (macro_stack_ptr > 0)
															{
																macro_stack_ptr--;
																yy_delete_buffer(YY_CURRENT_BUFFER);
																yy_switch_to_buffer(macro_stack[macro_stack_ptr]);
															}
															else if (--include_stack_ptr < 0)
																return rEOF;
															else
															{
																yy_delete_buffer(YY_CURRENT_BUFFER);
																yy_switch_to_buffer(include_stack[include_stack_ptr]);
																yylineno = include_lineno_stack[include_stack_ptr];
																free(gFileName[include_stack_ptr]);
															}
														}
	YY_BREAK
case 124:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 265 "Sources/rez_scanner.l"
error("Macro's with parameters are not supported yet");
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 266 "Sources/rez_scanner.l"
AddMacro(yytext);
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 267 "Sources/rez_scanner.l"

	YY_BREAK
case 127:
YY_RULE_SETUP
#line 268 "Sources/rez_scanner.l"
return yytext[0];
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 269 "Sources/rez_scanner.l"
ECHO;
	YY_BREAK
#line 1815 "Sources/rez_scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 497 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 497 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 496);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 269 "Sources/rez_scanner.l"


void AddMacro(char *s)
{
	char *m = s + strlen("#define");
	while (isspace(*m)) m++;
	
	char *c = m;
	while (!isspace(*c)) c++;
	*c++ = 0;
	while (isspace(*c)) c++;
	
	int mn = ST_AddIdent(m);
	
	gMacroTable[mn] = strdup(c);
} /* AddMacro */

void CopyBuf()
{
	size_t size = sbp - sBuf - sizeof(long);
	*(long *)sBuf = size;
	
	yylval = (int)malloc(size + sizeof(long));
	memcpy((void*)yylval, sBuf, size + sizeof(long));
} /* CopyBuf */
